Adds more ways to get help info in the terminal

diff --git a/bash/bash_aliases b/bash/bash_aliases
--- a/bash/bash_aliases
+++ b/bash/bash_aliases
@@ -21,6 +21,58 @@ alias add_cmd='${EDITOR} /Users/Saevon/Projects/Recipe/cmd.bash'
 # Misc
 ################
 
+# Manpage style help for builtin functions
+function helpman() {
+    help -m $@ | less
+}
+
+# Finds the given function, showing its contents if needed
+function helpfunc() {
+    function __show_help() {
+        echo 'helpfunc [-vh] FUNC_NAME'
+        echo ''
+        echo '  Gets information about the given function name (whether it exists)'
+        echo ''
+        echo '  -h    Help: Prints this help text'
+        echo '  -v    Verbose: Prints entire function contents'
+    }
+
+    local OPTIND=1
+    local verbose=false
+    while getopts ":hv" opt; do
+          case $opt in
+              h)
+                __show_help
+                return
+                ;;
+            v)
+                verbose=true
+                ;;
+            \?)
+                echo "Invalid option: -$OPTARG" >&2
+                ;;
+        esac
+    done
+
+    # Shift off the options and optional --.
+    shift "$((OPTIND-1))"
+
+    # Checks that we got a pos argument
+    if [ -z "$1" ]; then
+        __show_help
+        return
+    fi
+
+    # Main Code
+    if [ "${verbose}" == "true" ]; then
+        typeset -f | sed -n -e "/^$1 ()/,/^}/ p"
+    else
+        typeset -F | awk '{ print $3 }' | grep -E "\b($1)\b"
+    fi
+
+    unset -f __show_help
+}
+
 # set strongest compression level as ‘default’ for gzip
 alias gzip="gzip -9n"
 
